import { expect, test } from 'playwright/test'

test.describe('Benin V1 signup requirements', () => {
  for (const viewport of [{ width: 1440, height: 900 }, { width: 1024, height: 640 }, { width: 390, height: 844 }]) {
    test(`organizer password controls and removed identifier at ${viewport.width}px`, async ({ page }) => {
      await page.setViewportSize(viewport)
      await page.goto('/organizer-signup')
      await page.getByRole('button', { name: 'Essentiels uniquement' }).click()
      await expect(page.getByText(/Numéro IFU|SIRET|RCCM/)).toHaveCount(0)

      const password = page.getByLabel('Mot de passe', { exact: true })
      const confirmation = page.getByLabel('Confirmer le mot de passe', { exact: true })
      await password.fill('LocalTest123')
      await confirmation.fill('LocalTest123')
      await expect(password).toHaveAttribute('type', 'password')
      await page.getByRole('button', { name: 'Afficher le mot de passe', exact: true }).click()
      await expect(password).toHaveAttribute('type', 'text')
      await expect(password).toHaveValue('LocalTest123')
      await page.getByRole('button', { name: 'Masquer le mot de passe', exact: true }).click()
      await expect(password).toHaveAttribute('type', 'password')
      await expect(confirmation).toHaveAttribute('type', 'password')

      const help = page.getByRole('button', { name: 'Conditions du mot de passe' })
      await help.click()
      await expect(page.getByText('Au moins 8 caractères, une majuscule et un chiffre.')).toBeVisible()
      await help.press('Escape')
      await expect(help).toHaveAttribute('aria-expanded', 'false')
      const next = page.getByRole('button', { name: 'Continuer', exact: true })
      await next.scrollIntoViewIfNeeded()
      await expect(next).toBeInViewport()
      await expect(confirmation).toBeVisible()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    })
  }

  test('organizer requests only the account holder identity', async ({ page }) => {
    await page.goto('/organizer-signup')
    await page.getByRole('button', { name: 'Essentiels uniquement' }).click()
    await page.getByLabel('Nom de l’établissement ou nom commercial').fill('Studio Cotonou')
    await page.getByLabel('Email professionnel', { exact: true }).fill('contact@example.com')
    await page.getByLabel('Téléphone pro', { exact: true }).fill('0196123456')
    await page.getByLabel('Pas de lieu fixe (établissement en ligne / itinérant)', { exact: true }).check()
    await page.getByLabel('Adresse e-mail de connexion').fill('organizer@example.com')
    await page.getByLabel('Mot de passe', { exact: true }).fill('LocalTest123')
    await page.getByLabel('Confirmer le mot de passe', { exact: true }).fill('LocalTest123')
    await page.getByRole('button', { name: 'Continuer', exact: true }).click()
    await page.getByRole('combobox').first().click()
    await page.getByRole('option', { name: 'Boîte / Club', exact: true }).click()
    await page.getByPlaceholder('Cotonou', { exact: true }).fill('Cotonou')
    await page.getByRole('button', { name: 'Continuer', exact: true }).click()
    await page.getByRole('button', { name: 'Continuer', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Documents justificatifs' })).toBeVisible()
    await expect(page.getByText(/^Pièce d'identité du titulaire du compte/)).toBeVisible()
    await expect(page.getByText(/RCCM|KBIS|Document officiel de l'entreprise|Licence \/ justificatif/)).toHaveCount(0)
    await expect(page.locator('input[type=file]')).toHaveCount(1)
  })

  test('provider progresses from activities to explanation without tariffs', async ({ page }) => {
    await page.goto('/provider-signup')
    await page.getByRole('button', { name: 'Essentiels uniquement' }).click()
    await page.getByLabel('Prénom', { exact: true }).fill('Test')
    await page.getByLabel('Nom', { exact: true }).fill('Prestataire')
    await page.getByLabel('Téléphone', { exact: true }).fill('0196123456')
    await page.getByLabel('Ville', { exact: true }).fill('Cotonou')
    await page.getByLabel('Adresse e-mail de connexion', { exact: true }).fill('provider@example.com')
    await page.getByLabel('Mot de passe', { exact: true }).fill('LocalTest123')
    await page.getByLabel('Confirmation du mot de passe', { exact: true }).fill('LocalTest123')
    await page.getByRole('button', { name: 'Continuer', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Ton activité', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Photo & vidéo', exact: true }).click()
    await expect(page.getByText(/Numéro IFU|SIRET|RCCM|Tarifs \(/)).toHaveCount(0)
    await expect(page.getByText('Sur devis uniquement', { exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Continuer', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Comment ça marche' })).toBeVisible()
    await page.getByRole('button', { name: 'Continuer', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Documents justificatifs' })).toBeVisible()
    await page.getByRole('button', { name: 'Continuer', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Finaliser', exact: true })).toBeVisible()
  })
})
